global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['0.0.0.0:8889'] # so this is going to scrape collector???
    scrape_interval: 10s
    metrics_path: '/metrics'
