global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-metrics-collector:8889']
    scrape_interval: 10s
    metrics_path: '/metrics'
