apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: YOUR_IMAGE_NAME           # e.g., ghcr.io/your-org/your-service:tag
          ports:
            - containerPort: 8080          # Change if your service uses a different port
          envFrom:
            - configMapRef:
                name: go-service-config
